### ISSUE TITLE
Consider to migrate from super-linter to sqlfluff-github-actions

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health-sql#61]
Now we use super-linter image in pipeline to validate the quality of the sql queries https://github.com/mfvanek/pg-index-health-sql/blob/5a06f921c5f672d94922d249dcaa15e71016a9a8/.github/workflows/linter.yml#L21
The problems are:

- size of super-linter image is huge
- time for lint is high

The idea is to use sqlfluff directly

- via official image https://hub.docker.com/r/sqlfluff/sqlfluff
- or via official example https://github.com/sqlfluff/sqlfluff-github-actions

See https://github.com/sqlfluff/sqlfluff-github-actions/blob/main/menu_of_workflows/sunrise_movement/lint_models.yml

```yaml
name: Lint Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.3.6"
      - name: Lint models
        run: "sqlfluff lint models"
```
